### ISSUE TITLE
LHM-Karte

### ISSUE THREAD

**Issue by johnny-space** [ondics/ckan-docker-lhm#1]
### Feature description <a href="#feature-description" id="feature-description"/>
Es soll die LHM-Map verwendet werden, vgl. https://geoportal.muenchen.de/portal/master/

In CKAN werden an zwei Stellen Kartendarstellungen genutzt.
1. Im Data-Explorer, wenn aus einer CSV longitude und latitude dargestellt wird.
2. Wenn explizit eine WMS-Ressource dargestellt wird.

### Suggested solution <a href="#suggested-solution" id="suggested-solution"/>
CKAN-Doku: https://docs.ckan.org/projects/ckanext-spatial/en/latest/map-widgets.html
Aktuell sind die Werte laut [Code Snippets](#code-snippets) gesetzt.
Dadurch funktioniert bereits die Darstellung von WMS-Ressourcen, vgl. 2. oben.
Allerdings gibt es Wechselwirkungen mit `ckanext.spatial.common_map.custom.url`. 
Beim Test von 1. (s.o.) fehlt die Karte und in der Netzwerkanalyse kommt:
`HTTPS 500 Domain not found https://stamen-tiles-c.a.ssl.fastly.net/terrain/2/1/1.png`

### Code snippets <a href="#code-snippets" id="code-snippets"/>
```
grep -F "map." lhmchart/templates/ckan-configMap-local-ini.yaml | grep -v '#'
    ckanext.spatial.common_map.custom.url = https://tile.openstreetmap.org/{z}/{x}/{y}.png
    ckanext.spatial.common_map.attribution = Map tiles by <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors
    ckanext.spatial.common_map.type = wms
    ckanext.spatial.common_map.wms.url = https://geoportal.muenchen.de/geoserver/gsm/wms
    ckanext.spatial.common_map.wms.layer = gsm:g_stadtkarte_gesamt
    ckanext.spatial.common_map.wms.srs = EPSG:25832
```
### Task list
- [ ] evaluieren, ob geoportal.muenchen.de das Shema `/{z}/{x}/{y}` unterstützt (Anfrage ist bereits gestellt)
- [ ] Keys anpassen, so dass [Feature description](#feature-description) 1. und 2. gleichzeitig funktionieren
- [ ] Attribution für WMS hinzufügen `© <a href="https://www.geodatenservice-muenchen.de">Kommunalreferat – GeodatenService</a>, <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>`

**Comment by johnny-space** [comment]
Testdate für [Feature description](https://github.com/ondics/ckan-docker-lhm/issues/1#feature-description) 1. = CSV mit Koordinaten:
[toilettenkabinen-an-der-isar-2016-07-15.csv](https://github.com/ondics/ckan-docker-lhm/files/15026428/toilettenkabinen-an-der-isar-2016-07-15.csv)

Testdaten / Link für [Feature description](https://github.com/ondics/ckan-docker-lhm/issues/1#feature-description) 2. = WMS-Ressource: https://geoportal.muenchen.de/geoserver/gsm/luftbild/ows?service=WMS&version=1.3.0&request=GetCapabilities

**Comment by johnny-space** [comment]
Wird nochmals zwischen @rickelt und @johnny-space abgestimmt.
Test im Termin: box und xyz schließen sich aus.
